name: Auto image build CI/CD
on:
  push: 
     branches:
     - main
     - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: action/checkou@v3
    - name: Login 
      run: docker login -u devsathyaops -p ${{secrets.DOCKER_TOKEN}}
    - name: Push image to imagebuild repo
      if: ${{github.ref == 'refs/heads/main'}}
      run: docker build . --file Dockerfile --tag devsathyaops/imagebuild:latest && docker push devsathyaops/imagebuild:latest
    - name: Push image to auto image build repo
      if: ${{github.ref == 'refs/heads/master'}}
      run: docker build . --file Dockerfile --tag devsathyaops/auto_image_build:latest && docker push devsathyaops/auto_image_build:latest
